# Generated by Django 5.1.4 on 2024-12-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='nome',
            new_name='name',
        ),
    ]
